# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c31f09a085014bedaf99991ecc6fe39f81fdf5306db499730c3566db50489c937e436fba090ab55b6be6d86073a6ae53a6d7cc161ecb5aa8a3f9f9f7d5ab52d2

test:
  secret_key_base: 00da15c3323203675bc13d37a5e47aaabc0589033fc27b9b2560d9836802515dee632c2431b05dbfced711058e1b577854b49d4848c9a3ddeb0aa016462f3018

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
